package importer

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/aliramazanov/ghostci/internal/config"
	"go.yaml.in/yaml/v3"
)

func (r *Result) Ledger(w io.Writer, a Assumptions) {
	fmt.Fprintf(w, "imported %s from %s\n", countOf(len(r.Checks), "check"), r.UnitCount(len(r.Entries)))
	if len(r.Heavy) > 0 {
		fmt.Fprintf(w, "plus %d long-running steps, written commented out\n", len(r.Heavy))
	}
	fmt.Fprintln(w)

	order := []Outcome{
		Extracted, SkippedByCondition, DroppedAction, ToolchainAction,
		LocalAction, UnsupportedAction, NeedsReview, UnsupportedFeature,
	}
	for _, o := range order {
		if n := r.Count(o); n > 0 {
			fmt.Fprintf(w, "  %-20s %4d\n", o, n)
		}
	}

	if len(r.Toolchains) > 0 {
		fmt.Fprintf(w, "\ntoolchains pinned by CI:\n")
		for _, t := range r.Toolchains {
			fmt.Fprintf(w, "  %-12s %s\n", t.Name, t.Version)
		}
	}

	byReason := map[Outcome][]Entry{}
	for _, e := range r.Entries {
		switch e.Outcome {
		case NeedsReview, UnsupportedAction, UnsupportedFeature, SkippedByCondition:
			byReason[e.Outcome] = append(byReason[e.Outcome], e)
		}
	}
	for _, o := range []Outcome{NeedsReview, UnsupportedFeature, UnsupportedAction, SkippedByCondition} {
		entries := byReason[o]
		if len(entries) == 0 {
			continue
		}
		fmt.Fprintf(w, "\n%s:\n", o)
		for _, e := range dedupeEntries(entries, 12) {
			fmt.Fprintf(w, "  %s/%s: %s\n", e.Workflow, e.Job, e.Reason)
		}
		if len(entries) > 12 {
			fmt.Fprintf(w, "  ... and %d more\n", len(entries)-12)
		}
	}

	if len(r.NotTriggered) > 0 {
		fmt.Fprintf(w, "\nworkflows not imported, with the trigger that rules each out:\n")
		for _, s := range r.NotTriggered {
			fmt.Fprintf(w, "  %s\n", s)
		}
	}

	for _, warn := range r.Warnings {
		fmt.Fprintf(w, "\nwarning: %s\n", warn)
	}

	fmt.Fprintf(w, "\nlocal assumptions used to resolve conditions:\n")

	if r.GitLab {
		def := a.DefaultBranch
		if def == "" {
			def = "unknown, so rules comparing against it are left for review"
		}
		fmt.Fprintf(w, "  CI_COMMIT_BRANCH   = %s\n", strings.TrimPrefix(a.Ref, "refs/heads/"))
		fmt.Fprintf(w, "  CI_PIPELINE_SOURCE = %s (a job runs if any of these would run it)\n",
			strings.Join(pipelineSources, ", "))
		fmt.Fprintf(w, "  CI_DEFAULT_BRANCH  = %s\n", def)
		fmt.Fprintf(w, "  CI_PROJECT_PATH    = %s\n", a.Repository)

		return
	}

	if r.Azure || r.Circle || r.Bitbucket {

		fmt.Fprintf(w, "  branch = %s\n", strings.TrimPrefix(a.Ref, "refs/heads/"))
		fmt.Fprintf(w, "  conditions are not evaluated for this provider; a gated step is listed for review\n")

		return
	}

	fmt.Fprintf(w, "  github.ref        = %s\n", a.Ref)
	fmt.Fprintf(w, "  github.event_name = %s (a step runs if any of these would run it)\n", strings.Join(a.events(), ", "))
	fmt.Fprintf(w, "  github.repository = %s\n", a.Repository)
	fmt.Fprintf(w, "  runner.os         = %s\n", a.RunnerOS)
}

func dedupeEntries(entries []Entry, limit int) []Entry {
	seen := map[string]bool{}
	out := make([]Entry, 0, limit)
	for _, e := range entries {
		key := e.Workflow + "/" + e.Job + "/" + e.Reason
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, e)
		if len(out) == limit {
			break
		}
	}
	return out
}

func (r *Result) YAML(w io.Writer) error {
	cfg := config.Config{Checks: r.Checks}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "# Generated by ghostci from %s.\n", r.Origin())
	fmt.Fprintf(w, "# Review before committing: ghostci runs exactly what is listed here.\n\n")
	if _, err := w.Write(out); err != nil {
		return err
	}

	if err := r.writeHeavy(w); err != nil {
		return err
	}

	var deferred []Entry
	for _, e := range r.Entries {
		if e.Outcome == NeedsReview {
			deferred = append(deferred, e)
		}
	}
	if len(deferred) == 0 {
		return nil
	}

	fmt.Fprintf(w, "\n# Not imported, needs your review:\n")
	sort.Slice(deferred, func(i, j int) bool { return deferred[i].Workflow < deferred[j].Workflow })
	for _, e := range dedupeEntries(deferred, 40) {
		fmt.Fprintf(w, "#   %s/%s %q\n#     %s\n", e.Workflow, e.Job, trim(e.Step), e.Reason)
	}
	return nil
}

func (r *Result) writeHeavy(w io.Writer) error {
	if len(r.Heavy) == 0 {
		return nil
	}
	fmt.Fprintf(w, "\n# Long-running CI work, not enabled by default.\n")
	fmt.Fprintf(w, "# These are things CI really does. Uncomment any you want checked before a push.\n")

	for _, c := range r.Heavy {
		body, err := yaml.Marshal([]config.Check{c})
		if err != nil {
			return err
		}
		if why := r.HeavyReason[c.Name]; why != "" {
			fmt.Fprintf(w, "#\n#   %s\n", why)
		}
		for _, line := range strings.Split(strings.TrimRight(string(body), "\n"), "\n") {
			fmt.Fprintf(w, "# %s\n", line)
		}
	}
	return nil
}

func (r *Result) ExtractionRate() (extracted, runSteps int, pct float64) {
	for _, e := range r.Entries {
		switch e.Outcome {
		case Extracted:
			extracted++
			runSteps++
		case NeedsReview, SkippedByCondition:
			if !strings.HasPrefix(e.Step, "(") {
				runSteps++
			}
		}
	}
	if runSteps == 0 {
		return 0, 0, 0
	}
	return extracted, runSteps, float64(extracted) * 100 / float64(runSteps)
}

func countOf(n int, word string) string {
	if n == 1 {
		return "1 " + word
	}

	return fmt.Sprintf("%d %ss", n, word)
}
